### PR TITLE
New procedure for orthogonal orbitals

### PR DESCRIPTION
**Pull request by lcyyork**
## Description
This PR implements new orbital orthonormalization procedure for initial orbitals in Forte.
The new procedure keeps the relative ordering of the guess orbitals, that is, no canonicalization procedure is performed.
Now initial orbitals can come from a different basis set (see added test case `df-casscf-4-basis`).

To actually check these initial guess orbitals, some Python codes can be added in the input:
```
molecule Cr2{
Cr
Cr 1 3.5
symmetry c1
}

set globals{
scf_type             df
reference            rhf
guess                sadno
basis                cc-pwcvtz
df_basis_scf         def2-universal-jkfit
df_basis_mp2         def2-universal-jkfit
restricted_docc       [18]
active                [22]
}
escf, wfn = energy('scf', return_wfn=True)

from forte._forte import make_mo_space_info_from_map
mo_space_info = make_mo_space_info_from_map(wfn.nmopi(),
                                            Cr2.point_group().symbol(),
                                            {"ACTIVE": [22], "RESTRICTED_DOCC": [18]}, [])

# same basis, different geometry
wfn_old = wfn.from_file('wfn1.npy')  # cc-pwCVTZ @ 3.25 Angstrom
from forte.proc.orbital_helpers import ortho_orbs_new
wfn.Ca().copy(ortho_orbs_new(wfn.Ca(), wfn.S(), wfn_old.Ca(), mo_space_info))

# different basis, different geometry
wfn_old = wfn.from_file('wfn2.npy')  # cc-pVDZ @ 3.25 Angstrom
from forte.proc.orbital_helpers import basis_projection
Ca = basis_projection(wfn_old, wfn, mo_space_info)
wfn.Ca().copy(Ca)

# plot orbitals
orbs = [19 + i for i in range(22)]
set cubeprop_orbitals $orbs
cubeprop(wfn)
```

## User Notes
- [x] Add new orbital orthonormalization procedure.
- [x] No changes to compilation

## Checklist
- [x] Added/updated tests of new features and included a reference `output.ref` file
- [x] Removed comments in code and input files
- [x] Documented source code
- [x] Checked for redundant headers
- [x] Checked for consistency in the formatting of the output file
- [x] Documented new features in the manual
- [x] Ready to go!

### CODE REVIEW

**Comment by lcyyork** [comment]
I'd like to merge this first (if all tests pass) and then for PR #416. These two are related because the ordering active orbitals appears important.

**Comment by fevangelista** [comment]
Can we merge #418 before we merge this? I spent some time to make sure the logic in the restructured module is correct and this PR makes changes to the same files.

**Comment by lcyyork** [comment]
> Can we merge #418 before we merge this? I spent some time to make sure the logic in the restructured module is correct and this PR makes changes to the same files.

That's fine with me. Hopefully I do not need to redo everything in this PR and 416 after 418 is merged.

**Comment by fevangelista** [comment]
I can help merge the new lines in `objects_factory_psi4.py`, the rest should be fine.

**Comment by fevangelista** [comment]
Closing this because it was superseded by #423.

**Pull request closed without merging**
