### PR TITLE
Enable non-Hermitian MR-LDSRG(2)

### PR DESCRIPTION
**Pull request by brianz98**
## Description
Enable non-Hermitian MR-LDSRG(2), for both spin-integrated and spin-adapted versions.

## Checklist
- [x] Added/updated tests of new features and included a reference `output.ref` file
- [x] Enable non-Hermitian for SI code (this is just by removing a previous restriction)
- [x] Enable non-Hermitian for SA code
- [x] Enable non-Hermitian for SO code
- [x] Documented new features in the manual
- [x] Ready to go!

### CODE REVIEW

**Comment by fevangelista** [comment]
Can we get @lcyyork's blessing on this PR?

**Comment by brianz98** [comment]
Only DMRG tests are failing (need further investigation but unrelated to this PR). New tests all passing.

**Comment by brianz98** [comment]
Tests passing, ready to go. Non-Hermitian is enabled for all but three cases:
- Sequential transformation
- Quadratic commutator approximation
- Reference relaxation

**Comment by brianz98** [comment]
DMRG tests are now temporarily disabled due to github runners not playing well with them

**Comment by lcyyork** [comment]
Sorry for being late in the game. I would check if the results are correct or not by keeping the intermediate hamiltonian hermitian without adding it to the final DSRG hamiltonian.

**Pull request merged**
