### PR TITLE
fix cas when there is no restricted_docc

### PR DESCRIPTION
**Pull request by lcyyork**
## Description
Same as title.

## User Notes
- [x] Changes `CASSCF_ITERATIONS` to `CASSCF_MAXITER` to standardize with other parts of Forte
- [ ] Changes to compilation (if any)

## Implementation Notes
- [x] No longer transform all integrals for each iteration

## Checklist
- [x] Added test case `casscf-9` where there is no `frozen_docc` nor `restricted_docc`
- [x] Removed comments in code and input files
- [x] Documented source code
- [ ] Checked for redundant headers
- [ ] Checked for consistency in the formatting of the output file
- [x] Ready to go!

### CODE REVIEW

**Comment by lcyyork** [comment]
@fevangelista @huangm29 This should fix the CASSCF energy blowing up problem when there is no restricted_docc.

**Comment by fevangelista** [comment]
@lcyyork : I'll test it right away.

**Comment by fevangelista** [comment]
I pushed some changes that I wanted to do. I also found code that was redundant. Right now I would like to try to re-enable the no-printing mode, so that you only see the CASSCF iterations.

**Comment by fevangelista** [comment]
Maybe we should go one step further and move CASSCF out of forte_old_methods and send it to the python side. I am not sure how to trigged CASSCF, maybe we just need a option like `optimize_mos` or `do_casscf`.

**Comment by lcyyork** [comment]
Let me merge some of my changes in the casscf_clean_up branch to this branch.

**Comment by fevangelista** [comment]
I think I am done with my changes. I could not yet fix the printing issue but that's a minor esthetic issue.

**Comment by lcyyork** [comment]
So I merge my casscf_clean_up branch changes to here. Basically I avoid the full integral transformation for each macro iteration since only a tiny fraction of integrals are needed.

**Comment by lcyyork** [comment]
I am finally done with the changes. Let us wait and see what TravisCI says.

**Comment by lcyyork** [comment]
@henankf223 I add Fock build in CASSCF now. You may want to take a look if you have not yet make it work.

**Pull request merged**
