### PR TITLE
Print the reference energy immediately after recomputing.

### PR DESCRIPTION
**Pull request by tyzhang1993**
This PR prints the recomputed reference energy before the DSRG iterations.
It enables estimation of results during computation when a job takes a long time.
- [x] Ready to go.

### CODE REVIEW

**Comment by lcyyork** [comment]
I would probably just say "Updated reference energy E(0) = ...".

**Comment by lcyyork** [comment]
It seems travis yml file is failing.

**Comment by tyzhang1993** [comment]
@lcyyork Thanks! Changed the wording.
The travis problem seems to be problem with psi4's endorsed plugin.

**Comment by fevangelista** [comment]
Yes, I am working on making Forte and Psi4 work together after the update of pybind11.

**Pull request merged**
