### PR TITLE
New 2-Step MCSCF Code

### PR DESCRIPTION
**Pull request by lcyyork**
## Description
This PR adds a new 2-step MCSCF code in Forte.

- The new 2-step MCSCF consists of macro (solve CI for given orbital coefficients) and micro (optimize orbitals for given CI coefficients) iterations.
- In macro iterations, orbitals are extrapolated using DIIS. In micro iterations, orbital optimization is performed using 
limited-memory BFGS (L-BFGS).
- The number of iterations for L-BFGS minimization is initially set to `CASSCF_MICRO_MINITER` and changes during the macro iterations but it never exceeds `CASSCF_MICRO_MAXITER`.
- Evaluation of orbital gradient and diagonal Hessian is computed in `CASSCF_ORB_GRAD` class.
- The implementation uses `JK` technology of Psi4 (i.e. OK to use PK, DF, DISKDF, CD integrals) and does support `FCIDUMP` format.
- Frozen-core approximation is supported for both energy and gradient.
- Single reference RHF/ROHF can also be computed using the current implementation.
- An orbital orthonormality test is performed when a `ref_wfn` is passed. If the incoming orbitals are not from the current geometry (**C**^T **S** **C** != 1), an SCF calculation and orbital orthonormality procedure will be performed. As such, the incoming orbitals will be treated as starting guess for MCSCF.

## TODO List
- [x] Adapt GAS (semicanonicalization, internal orbital rotation).
- [ ] Add natural orbital support in `SemiCanonical` class.
- [ ] Find better ways to handle mixed orbitals in TPDM transformation (MCSCF gradient with HF frozen-core orbitals).
- [x] Skip ForteIntegral build for CASSCF and store the JK object in ForteIntegral.
- [ ] The CI problem should read the CI coefficients from previous macro iterations. The CI coefficients can also be extrapolated using DIIS.
- [ ] Analytic energy gradient for state-averaged MCSCF. The nuclear gradients target only one of the state.
- [x] Add support of using `FCIDUMP` integrals. This is very inefficient multiple 2-e integral transformation.
- [ ] Optimize for `FCIDUMP` and `Conventional` integrals (only MO two-electron integrals in chemists notation). We can store only the alpha-beta case and the alpha-alpha/beta-beta can be computed when needed.

## User Notes
- [x] Several keywords to control the convergence behavior are added, including `CASSCF_MICRO_MINITER`, `CASSCF_MICRO_MAXITER`, `CASSCF_MAX_ROTATION`, `CASSCF_DIIS_MIN_VEC`, etc. Please check `register_forte_options.py` for more options.
- [x] Note that we no longer use `CASSCF_DO_DIIS` to enable/disable DIIS, but just use `CASSCF_DIIS_START`.
- [x] Add the `CASSCF_ORB_GRAD` class for the actual computation of MCSCF orbital gradient and diagonal Hessian.
- [x] Add a general function for printing options in `helpers/printing.h`.
- [x] Add a L-BFGS class along with a class to store L-BFGS parameters. The L-BFGS is tested on even-order Rosenbrock function, which is also available in Forte now. See `l-bfgs_rosenbrock` test case.
- [x] Add a RHF-based CPSCF class where the linear equation is casted to quadratic minimization and solved using L-BFGS.
- [x] Rearrange some of the `backtransform_tpdm` code and add support for restricted formalism. Removed `sort_so_tpdm ` and `setup_tpdm_buffer` functions from compilation, which appear identical to those in Psi4.
- [x] Add a test case for frozen-core analytic energy gradient on nitrogen molecule. See `casscf-gradient-2` and `casscf-gradient-3` test case.
- [x] The DF integrals are supported. **However, there is a small discrepancy between analytic energy gradient and that of finite difference.** I think this is a problem from DF derivative integrals in Psi4.
- [x] Add Python functions to read/write orbitals.
- [x] Need to update Psi4 to 1.4a2.dev224 (early 2020) but preferably latest 1.4a2.dev1058 (late 2020).

## Checklist
- [x] Added tests of new features
- [x] Removed comments in code and input files
- [x] Documented source code. The code is well documented.
- [x] Checked for redundant headers
- [x] Checked for consistency in the formatting of the output file
- [x] Documented new features in the manual
- [x] Ready to go!

### CODE REVIEW

**Comment by fevangelista** [comment]
I am OK with merging the two keywords. However, I think that it should not be the responsibility of the user to set this during a computation, it can only cause errors and confusion. Let me ask: was canonicalization previously disabled for selected CI-SCF because of the GAS partitioning (which was destroyed by semicanonicalization before the recent changes to the MOSpaceInfo class) or because active-active rotations change the energy when the determinant space is not complete? Maybe we should have a zoom chat about this point.

**Comment by lcyyork** [comment]
> I am OK with merging the two keywords. However, I think that it should not be the responsibility of the user to set this during a computation, it can only cause errors and confusion. Let me ask: was canonicalization previously disabled for selected CI-SCF because of the GAS partitioning (which was destroyed by semicanonicalization before the recent changes to the MOSpaceInfo class) or because active-active rotations change the energy when the determinant space is not complete? Maybe we should have a zoom chat about this point.

I do not know. I think this keyword is added only recently due to addition of GAS technology. I will adapt the GAS partitions for canonicalization. However, it is in user's hand to choose what kind of canonicalization to use, whether semicanonical, or natural, or bypassing this procedure.

**Comment by lcyyork** [comment]
@fevangelista Any idea why Travis failed? The compilation seems OK but the push_options_to_psi failed.

**Comment by lcyyork** [comment]
@fevangelista This PR is ready. Please take a look. The TODOs will be addressed later in other new branches.

@huangm29 I have not looked into the GASSCF procedure carefully but it would be nice if it can be added to the new code by tuning the internal orbital rotations.

**Comment by lcyyork** [comment]
@fevangelista Tests (standard group) on my computer
```
Summary:
    ============================================================================
    TEST                                                         RESULT TIME (s)
    ----------------------------------------------------------------------------
    ACI-1........................................................PASSED    3.4
    ACI-3........................................................PASSED    2.1
    ACI-4........................................................PASSED    9.1
    ACI-5........................................................PASSED    2.7
    ACI-8........................................................PASSED   10.0
    ACI-9........................................................PASSED    1.4
    ACI-12.......................................................PASSED    2.0
    ACI-14.......................................................PASSED    2.2
    ACI-18.......................................................PASSED    2.9
    ACI_SCF-1....................................................PASSED    2.2
    ACI-FULL-PT2-1...............................................PASSED    1.5
    ACI-2........................................................PASSED    6.2
    ACI-6........................................................PASSED    5.3
    ACI-10.......................................................PASSED    4.1
    ACI-11.......................................................PASSED    7.2
    ACI-13.......................................................PASSED    7.0
    ACI-15.......................................................PASSED    6.8
    ACI-16.......................................................PASSED    4.5
    ACI-17.......................................................PASSED    4.1
    ACI-19.......................................................PASSED    3.5
    ACI-LOCAL-20.................................................PASSED   11.0
    ASCI-2.......................................................PASSED    1.8
    ASCI-3.......................................................PASSED    1.7
    AVAS-3.......................................................PASSED    2.2
    AVAS-5.......................................................PASSED    2.2
    AVAS-1.......................................................PASSED    2.4
    AVAS-2.......................................................PASSED    2.4
    AVAS-4.......................................................PASSED    2.2
    EMBEDDING-1..................................................PASSED    2.3
    EMBEDDING-3..................................................PASSED    2.0
    EMBEDDING-4..................................................PASSED    2.4
    EMBEDDING-5..................................................PASSED    5.3
    EMBEDDING-2..................................................PASSED    2.2
    CASSCF-7.....................................................PASSED    3.6
    DF-CASSCF-1..................................................PASSED    2.2
    CASSCF-FCIDUMP-1.............................................PASSED    6.6
    CASSCF-GRADIENT-1............................................PASSED    1.6
    CASSCF-GRADIENT-3............................................PASSED    5.8
    CASSCF-1.....................................................PASSED    1.9
    CASSCF-2.....................................................PASSED    1.5
    CASSCF-3.....................................................PASSED    2.0
    CASSCF-4.....................................................PASSED    2.1
    CASSCF-5.....................................................PASSED    2.4
    CASSCF-6.....................................................PASSED    2.4
    CASSCF-9.....................................................PASSED    2.0
    CASSCF-GRADIENT-2............................................PASSED    2.9
    CD-DSRG-MRPT2-7-SA...........................................PASSED    2.9
    CD-DSRG-MRPT2-3..............................................PASSED    1.6
    CD-DSRG-MRPT2-4..............................................PASSED    2.5
    CD-DSRG-MRPT2-6..............................................PASSED    2.2
    DIAG-ALG-1-DYNAMIC...........................................PASSED    3.8
    DIAG-ALG-2-DYNAMIC...........................................PASSED    3.6
    DIAG-ALG-1-SPARSE............................................PASSED    1.5
    DIAG-ALG-2-SPARSE............................................PASSED    1.6
    DF-DSRG-MRPT2-1..............................................PASSED    1.8
    DISKDF-DSRG-MRPT2-4..........................................PASSED    2.5
    DF-ACI-DSRG-MRPT2-2..........................................PASSED    1.9
    DF-DSRG-MRPT2-2..............................................PASSED    2.0
    DF-DSRG-MRPT2-6..............................................PASSED    2.3
    DF-DSRG-MRPT2-THREADING2.....................................PASSED    2.2
    DISKDF-DSRG-MRPT2-1..........................................PASSED    1.9
    DISKDF-DSRG-MRPT2-3..........................................PASSED    1.8
    DISKDF-DSRG-MRPT2-THREADING4.................................PASSED    3.9
    DF-ACI-DSRG-MRPT2-1..........................................PASSED    2.2
    DSRG-MRPT2_SPIN_ADAPTED-1....................................PASSED    1.5
    DSRG-MRPT2-8-SA..............................................PASSED    2.6
    DSRG-MRPT2-10-CO.............................................PASSED    4.2
    DSRG-MRPT2-13................................................PASSED    2.4
    ACI-DSRG-MRPT2-3.............................................PASSED    2.0
    DSRG-MRPT2-FCIDUMP-1.........................................PASSED    1.4
    DSRG-MRPT2-GRAD-FINDIFF-1....................................PASSED    3.9
    DSRG-MRPT2-1.................................................PASSED    1.4
    DSRG-MRPT2-2.................................................PASSED    1.7
    DSRG-MRPT2-5.................................................PASSED    2.0
    DSRG-MRPT2-6.................................................PASSED    2.5
    DSRG-MRPT2-7-CASSCF-NATORBS..................................PASSED    5.3
    DSRG-MRPT2-11-SA-C2H4........................................PASSED    4.0
    ACI-DSRG-MRPT2-1.............................................PASSED    2.3
    ACI-DSRG-MRPT2-2.............................................PASSED    1.8
    ACI-DSRG-MRPT2-4.............................................PASSED    9.7
    DSRG-MRPT2-10-CO-FCIDUMP.....................................PASSED    3.0
    DSRG-MRPT2-OPT-FINDIFF-1.....................................PASSED    7.1
    DSRG-MRPT3-7-CO..............................................PASSED    7.8
    DSRG-MRPT3-9.................................................PASSED    3.7
    DSRG-MRPT3-1.................................................PASSED    3.5
    DSRG-MRPT3-2.................................................PASSED    2.8
    DSRG-MRPT3-5.................................................PASSED    4.9
    ACI-DSRG-MRPT3-1.............................................PASSED    9.3
    FCI-1........................................................PASSED    1.8
    FCI-7........................................................PASSED    3.3
    FCI-EX-1.....................................................PASSED    3.2
    FCI-RDMS-1...................................................PASSED    1.6
    FCI-2........................................................PASSED    1.7
    FCI-3........................................................PASSED    1.5
    FCI-4........................................................PASSED    1.6
    FCI-5........................................................PASSED    2.3
    FCI-8........................................................PASSED    1.5
    FCI-ECP-1....................................................PASSED    2.0
    FCI-ECP-2....................................................PASSED    1.7
    FCI-ONE-ELECTRON.............................................PASSED    1.5
    FCI-RDMS-2...................................................PASSED    1.8
    INTEGRALS-3..................................................PASSED    1.8
    INTEGRALS-4..................................................PASSED    1.8
    INTEGRALS-FCIDUMP-1..........................................PASSED    1.5
    INTEGRALS-1..................................................PASSED    1.8
    INTEGRALS-2..................................................PASSED    2.0
    INTEGRALS-5..................................................PASSED    1.7
    INTEGRALS-FCIDUMP-2..........................................PASSED    1.2
    INTEGRALS-FCIDUMP-3..........................................PASSED    1.1
    INTEGRALS-FCIDUMP-4..........................................PASSED    1.2
    INTEGRALS-FCIDUMP-5..........................................PASSED    1.2
    INTEGRALS-FCIDUMP-6..........................................PASSED    1.8
    MR-DSRG-PT2-1................................................PASSED    1.6
    MR-DSRG-PT2-3................................................PASSED    1.5
    MR-DSRG-PT2-2................................................PASSED    1.5
    MRDSRG_SO-1..................................................PASSED    8.5
    MRDSRG-LDSRG2-QC-DF-2........................................PASSED    6.5
    MRDSRG-LDSRG2-DF-SEQ-NIVO-1..................................PASSED    7.3
    MRDSRG-LDSRG2-DF-3...........................................PASSED   58.6
    MRDSRG-LDSRG2-DF-NIVO-1......................................PASSED   65.1
    MRDSRG-LDSRG2-1..............................................PASSED   22.9
    MRDSRG-LDSRG2-QC-2...........................................PASSED   20.5
    MRDSRG-PT2-2.................................................PASSED    2.5
    MRDSRG-PT2-1.................................................PASSED    2.0
    MRDSRG-PT2-4.................................................PASSED    6.8
    MRDSRG-SPIN-ADAPTED-1........................................PASSED    6.0
    MRDSRG-SPIN-ADAPTED-3........................................PASSED   15.9
    MRDSRG-SPIN-ADAPTED-2........................................PASSED   25.3
    MRDSRG-SPIN-ADAPTED-4........................................PASSED   13.5
    MRDSRG-SPIN-ADAPTED-5........................................PASSED   66.4
    MRDSRG-SPIN-ADAPTED-PT2-1....................................PASSED    3.6
    MRDSRG-SPIN-ADAPTED-PT2-2....................................PASSED    2.0
    MRDSRG-SPIN-ADAPTED-PT2-5....................................PASSED    4.2
    MRDSRG-SPIN-ADAPTED-PT2-3....................................PASSED   21.2
    MRDSRG-SPIN-ADAPTED-PT2-4....................................PASSED    2.6
    MRDSRG-SPIN-ADAPTED-PT3-1....................................PASSED    2.3
    MRDSRG-SPIN-ADAPTED-PT3-2....................................PASSED    3.9
    L-BFGS_ROSENBROCK............................................PASSED    1.3
    PCI-1........................................................PASSED    1.8
    PCI-3........................................................PASSED    1.8
    PCI-4........................................................PASSED    1.9
    PCI-6........................................................PASSED    1.7
    PCI-8........................................................PASSED    1.8
    GASCI-1......................................................PASSED    1.7
    GASCI-2......................................................PASSED    1.7
    GASACI-1.....................................................PASSED    2.5
    GASACI-4.....................................................PASSED    1.8
    GASCI-3......................................................PASSED    1.7
    GASACI-2.....................................................PASSED    2.1
    GASACI-3.....................................................PASSED    1.8
    GASSCF-1.....................................................PASSED    2.3
    GASSCF-3.....................................................PASSED    1.8
    SA-GASSCF-1..................................................PASSED    3.0
    SA-GASSCF-2..................................................PASSED    2.0
    SA-GASSCF-DSRG-MRPT2-1.......................................PASSED    2.9
    GASSCF-2.....................................................PASSED    2.0
    GASSCF-DSRG-MRPT2-1..........................................PASSED    2.8
    SA-GASSCF-3..................................................PASSED    2.3
    ============================================================================

Total time:  755.8 s

Tests: All passed (158 tests)
```

**Comment by fevangelista** [comment]
Thanks. I'll review as soon as I have a chance.

**Comment by lcyyork** [comment]
All standard tests pass on my computer.

**Pull request merged**
