### PR TITLE
DWSA-DSRG-PT

### PR DESCRIPTION
**Pull request by lcyyork**
I move the old DWMS branch to here because the history was messed up.

### Goals
- [x] DWMS-DSRGPT Class
    - [x] Move the MS/XMS DSRG-PT2 to DWMS class.
    - [x] Add DWSA algorithm
    - [x] Enable PT2/PT3 for DWSA parametrization
    - [x] Clean up
    - [x] Add test cases
        - [x] dwms-dsrgpt-1-sa: test equivalence between DWSA-DSRG-PT2 (zeta = 0) and SA-DSRG-PT2
        - [x] dwms-dsrgpt-2-sa: test PT2 SA and XSA algorithms on LiF
        - [x] dwms-dsrgpt-3-sa: test PT3 SA and XSA algorithms on LiF
        - [x] dwms-dsrgpt-4-sa: test different dwms references (PT2, PT3)
        - [x] dwms-dsrgpt-5-ms: test equivalence between DW(X)MS-DSRG-PT2 (zeta -> inf) and (X)MS-DSRG-PT2
        - [x] dwms-dsrgpt-6-ms: test PT2 MS and XMS algorithms on LiF
        - [x] dwms-dsrgpt-7-ms: test different dwms references (PT2, PT3)
        - [x] dwms-dsrgpt-8-separated: deprecated test cases for separate diagonalization
        - [x] dwms-dsrgpt-9-sa-C6H6: benzene excitations using DWSA-DSRG-PT2(zeta = 1000)/def2-SVP
----
- [x] FCI_MO Class
    - [x] Write computed densities on disk if doing DWMS-DSRG-PT
    - [x] Clean up
----
- [x] ACTIVE_DSRGPT2 Class
    - [x] Adapt to cleanups of FCI_MO
    - [x] Move ACTIVE_DSRGPT2 Class inside mrdsrg-spin-integrated folder
    - [x] Clean up

----

### Minor Changes
- [x] Loosen the semicanonical criteria if using Cholesky integrals.
- [x] Change `resize` to `assign` to ensure zero initial values in CI_RDMS class.

----
- [x] Ready to GO

### CODE REVIEW

**Comment by fevangelista** [comment]
@lcyyork: Perhaps you already did it: Can you make sure all files are formatted?

**Comment by lcyyork** [comment]
@fevangelista I have formatted all files that are changed in this PR. Do you want me to format all forte files? I am afraid there will be many conflicts for other PRs.

**Comment by fevangelista** [comment]
@lcyyork: I did not look into these conflicts. Are they trivial or involved?

**Comment by fevangelista** [comment]
@lcyyork: I neglected this branch. Is this up to date and synced with your local copy?

**Comment by lcyyork** [comment]
@fevangelista It is up to date and the iterative procedure is updated in this branch. Depending on what we are going to do with the paper, I may update the naming of different DW algorithms later.

**Comment by lcyyork** [comment]
@fevangelista I was wondering if we should merge this to master because I pushed all test cases changes here, which are affected by the latest psi4. If we want to rename some of the DW algorithms, I can create a new PR.

**Pull request merged**
