### PR TITLE
Corrected performance test.

### PR DESCRIPTION
**Pull request by tyzhang1993**
This PR corrected the performance tests.

- [x] Ready to go.

### CODE REVIEW

**Comment by tyzhang1993** [comment]
@fevangelista (i) I think that was because of the basis set change. These tests are 3 years old and pretty outdated.
(ii) I found that originally in these test cases, some of them have result check, some of them do not. In order to have a clean output, I commented out all the result checks for I think the correctness of algorithm should be checked in `test/method` rather than in the performance test. I can add them back if you think that is better idea.

**Comment by fevangelista** [comment]
I think we should reintroduce the tests to make sure the timing is for a procedure that ran correctly.

**Comment by tyzhang1993** [comment]
Good point, I will.

**Comment by jeffschriber** [comment]
Code looks good, but could you pull/rebase master to make sure travis compiles and runs?

**Comment by tyzhang1993** [comment]
@jeffschriber I actually rebased master. Travis fails because of psi4 compiling error rather than forte problem.

**Comment by jeffschriber** [comment]
Oh I understand now. Yes we can merge once psi is working.

**Pull request merged**
