### PR TITLE
add dsrg docs

### PR DESCRIPTION
**Pull request by lcyyork**
## Description
Add Documentation for DSRG.
Since the DWMS code is not ready, I mostly left related options and test cases as future work.

- [x] Ready to go

### CODE REVIEW

**Comment by lcyyork** [comment]
This is not yet ready for merge.

**Comment by tyzhang1993** [comment]
@lcyyork Let me know if you want me to work on part of it.

**Comment by lcyyork** [comment]
@tyzhang1993 Hi Sam, I would appreciate if you could write a brief theory summary of the sequential transformation and NIVO, including some pros and cons.

**Comment by tyzhang1993** [comment]
@lcyyork Sure! I'll go ahead to do it.

**Comment by lcyyork** [comment]
@tyzhang1993 Hi Sam,  thanks for the changes. Currently options are separated according to sections. I have moved your changes to the "Theoretical Variants and Technical Details" section. Please also add the some theory description there.

If you have some more time, would you mind to help me change the "4. MR-DSRG Test Cases" in "A Complete List of DSRG Test Cases" to a Table similar to "1. DSRG-MRPT2 Test Cases"? It may be good to also list those that are untested.

It will probably still take me several days to finish the rest of the manual. At the end, you and Francesco may need to proofread all the text.

**Comment by tyzhang1993** [comment]
@lcyyork Thanks. I actually realized I put those in the wrong section immediately after I committed.

**Comment by lcyyork** [comment]
@tyzhang1993 @fevangelista Hi guys, I think I am done here. Would you mind to proofread the text. Feel free to leave comments.

I am not sure what is the better way to view the doc on your own computer. The simplest might be clone my fork and make doc there.

**Comment by fevangelista** [comment]
This is an outstanding PR! Thanks for the hard work documenting the DSRG features.

**Comment by fevangelista** [comment]
I have some comments for improvements, but we can leave that for the next PR.

**Pull request merged**
