### PR TITLE
DF-MP2 natural orbitals

### PR DESCRIPTION
**Pull request by lcyyork**
## Description
DF-MP2 natural orbitals

## User Notes
- [x] Add DF support for MP2 natural orbitals
- [x] Add a function to split the vector to several subvectors
- [x] Other minor changes or typo fixes

## Checklist
- [x] Added/updated tests of new features and included a reference `output.ref` file
- [x] Removed comments in code and input files
- [x] Documented source code
- [x] Checked for redundant headers
- [x] Checked for consistency in the formatting of the output file
- [x] Ready to review 
- [x] Ready to go!

### CODE REVIEW

**Comment by JonathonMisiewicz** [comment]
Why are we building the MP2 natural orbitals in Forte rather than getting the natural orbitals from Psi?

**Comment by lcyyork** [comment]
> Why are we building the MP2 natural orbitals in Forte rather than getting the natural orbitals from Psi?

I am not sure how to run MP2 natural orbital using Psi4. Do you have an input example?

**Comment by lcyyork** [comment]
Thank you for the suggestion. By SO, do you mean symmetry-adapted AO?

Another to clarify is that Forte does support MP2-NO, just without DF. I just want it to suggest an active space for me.

**Comment by JonathonMisiewicz** [comment]
_sigh_ Good question. Neither code supports symmetry, which is another obstacle to Forte using them for active space purposes. For DF-MP2 with symmetry, you would need a new code.

I meant "Symmetry Orbital" when I wrote my last message, but "Atomic Orbital" would be more accurate.

**Comment by fevangelista** [comment]
Nice contribution. I think that in the long run we need to refactor this, maybe adding MP2 to Forte as its own method. Will put on my list of things to review.

**Comment by fevangelista** [comment]
The MP2 NOs test case seems to be failing. I'll wait for you to fix it before taking a look.

**Comment by lcyyork** [comment]
> The MP2 NOs test case seems to be failing. I'll wait for you to fix it before taking a look.

I think it's fixed. Please take a look when you have some time to kill.

**Review by fevangelista — APPROVED** [review]

**Pull request merged**
